##
# This file is part of the pl.wrzasq.parent.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2025 © by Rafał Wrzeszcz - Wrzasq.pl.
##

version: 2
updates:
    -
        package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "daily"
        groups:
            maven-plugins:
                patterns:
                    - "org.apache.maven:*"
                    - "org.apache.maven.plugins:*"
            kotlin:
                patterns:
                    - "org.jetbrains.kotlin:*"
            mockk:
                patterns:
                    - "io.mockk:*"
            junit:
                patterns:
                    - "org.junit.jupiter:*"
    -
        package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
